import StyledComponentsRegistry from "@/lib/registry"
import type { Metadata } from "next"
import { Poppins, Lato } from "next/font/google"

import { Providers } from "./providers"

const lato = Lato({ 
  weight: ["400"], 
  subsets: ["latin"],
  variable: "--font-lato"
})
const poppins = Poppins({ 
  weight: ["400"], 
  subsets: ["latin"],
  variable: "--font-poppins"
 })
const poppins700 = Poppins({ 
  weight: ["700"], 
  subsets: ["latin"],
  variable: "--font-poppins700"
 })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${poppins.variable} ${poppins700.variable}`}>
        <StyledComponentsRegistry> 
          <Providers>{children}</Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
